Kinda fixed the Spinner
bautistaaa/typehero pull request #522
Opened 2023-08-30 20:52 UTC by ggrandi

This fix is very much a patch (it just makes the button say open test cases)

It has unearthed that we need to change how we do the typechecks. Down the line, I think we should embed the typescript compiler and run it on submit.

2023-08-30 20:57 UTC, bautistaaa commented
does kinda mean its still breaking in some cases? 

if im understanding correctly i know we show a spinner on initialization so it can typecheck and show the appropriate squiggles. how would that work if we defer to clicking submit

2023-08-31 07:00 UTC, ggrandi commented
Kinda means that it is working now but the fix real fix would be that we fundamentally have to redo the logic for it.

My thoughts for doing this properly are to essentially run `tsc --noEmit` on the files in the browser so that we don't need to have the test cases panel open for them to work. I think this might also be necessary down the line if we want to add the the type benchmarking stuff

2023-08-31 18:03 UTC, bautistaaa approved these changes

2023-08-31 18:05 UTC, QuiiBz requested changes

2023-08-31 18:05 UTC, QuiiBz commented on packages/monaco/src/index.tsx
> +  console.log(props.submissionDisabled, tsErrors === undefined);
To remove

2023-08-31 18:48 UTC, bautistaaa commented on packages/monaco/src/index.tsx
> +  console.log(props.submissionDisabled, tsErrors === undefined);
fixed

2023-08-31 18:52 UTC, QuiiBz approved these changes

2023-08-31 18:53 UTC, merged